name: Vercel Status Updates

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]

jobs:
  notify-vercel:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    - name: 'notify vercel'
      uses: 'vercel/repository-dispatch/actions/status@v1'
      with:
        name: 'Vercel - topgrill: lint'
